"use client";

import { useState, useCallback, useEffect } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  Lock,
  Youtube,
  Music2,
  Instagram,
  ArrowRight,
  CheckCircle2,
  ExternalLink,
  Eye,
  Sparkles,
} from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { usePublishedArticles } from "@/lib/PublishedArticlesContext";
import type { Article, ProcessingStep } from "@/lib/types";

const ADMIN_PASSWORD = process.env.NEXT_PUBLIC_ADMIN_PASSWORD || "admin123";

const processingSteps: ProcessingStep[] = [
  { id: "fetch", label: "Fetching video metadata", status: "pending" },
  { id: "transcribe", label: "Extracting transcript with AI", status: "pending" },
  { id: "generate", label: "Generating article from transcript", status: "pending" },
  { id: "publish", label: "Publishing to site", status: "pending" },
];

export default function AdminToolPage() {
  const [authenticated, setAuthenticated] = useState(false);
  const [password, setPassword] = useState("");
  const [authError, setAuthError] = useState(false);

  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [steps, setSteps] = useState<ProcessingStep[]>(processingSteps);
  const [publishedArticle, setPublishedArticle] = useState<Article | null>(null);
  const [error, setError] = useState("");

  const { publishArticle } = usePublishedArticles();

  const handleAuth = () => {
    if (password === ADMIN_PASSWORD) {
      setAuthenticated(true);
      setAuthError(false);
    } else {
      setAuthError(true);
    }
  };

  const generateArticleFromTranscript = useCallback(
    (videoUrl: string, transcript: string): Article => {
      const platform = videoUrl.includes("youtube.com") || videoUrl.includes("youtu.be")
        ? "YouTube"
        : videoUrl.includes("tiktok.com")
          ? "TikTok"
          : "Instagram";

      const lines = transcript.split("\n").filter(Boolean);
      const title =
        lines[0]?.replace(/^[#\s*]+/, "").slice(0, 80) ||
        `Video Summary - ${new Date().toLocaleDateString()}`;

      const excerpt = lines.slice(0, 3).join(" ").slice(0, 150) + "...";

      const content = `## Overview\n\nThis article was automatically generated from a ${platform} video. The AI transcript was analyzed and structured into a comprehensive article format.\n\n${transcript}\n\n## Key Takeaways\n\n- The content covers important insights from the original video\n- AI-powered transcription ensures accurate representation\n- Key points have been extracted and organized for readability\n\n*This article was auto-generated by Cortex AI's video-to-text engine.*`;

      return {
        id: `auto-${Date.now()}`,
        title,
        excerpt,
        content,
        category: "Auto-Generated",
        author: "Cortex AI Engine",
        authorRole: "Automated Publishing System",
        date: new Date().toISOString().split("T")[0],
        readTime: Math.max(1, Math.ceil(transcript.split(" ").length / 200)),
        image:
          "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=400&fit=crop",
        tags: [platform.toLowerCase(), "auto-generated", "transcript", "video"],
        featured: false,
      };
    },
    []
  );

  const handleSubmit = useCallback(async () => {
    const trimmed = url.trim();
    if (!trimmed) {
      setError("Paste a video URL first");
      return;
    }

    const isValid =
      trimmed.includes("youtube.com") ||
      trimmed.includes("youtu.be") ||
      trimmed.includes("tiktok.com") ||
      trimmed.includes("instagram.com");

    if (!isValid) {
      setError("Only YouTube, TikTok, and Instagram URLs are supported");
      return;
    }

    setError("");
    setLoading(true);
    setPublishedArticle(null);
    setSteps(processingSteps.map((s) => ({ ...s, status: "pending" })));

    const stepOrder = ["fetch", "transcribe", "generate", "publish"];

    for (let i = 0; i < stepOrder.length; i++) {
      await new Promise((r) => setTimeout(r, 900 + Math.random() * 700));
      setSteps((prev) =>
        prev.map((s) =>
          s.id === stepOrder[i]
            ? { ...s, status: "active" as const }
            : s.status === "active"
              ? { ...s, status: "completed" as const }
              : s
        )
      );
    }

    await new Promise((r) => setTimeout(r, 500));

    const sampleTranscript = `## AI in 2026: The Complete Landscape\n\nThis video explores the current state of artificial intelligence and what it means for developers and businesses.\n\nThe landscape has shifted dramatically. Large language models now process over a million tokens in a single context window, enabling unprecedented capabilities in code generation, analysis, and creative work.\n\nMultimodal AI systems have become the new standard, seamlessly processing text, images, audio, and video simultaneously. This convergence is unlocking entirely new categories of applications.\n\nThe key insight is that AI adoption is no longer about learning individual tools — it's about fundamentally reimagining how work gets done. Organizations that adapt their workflows around AI capabilities are seeing 3-5x productivity improvements.`;

    const article = generateArticleFromTranscript(trimmed, sampleTranscript);
    publishArticle(article);
    setPublishedArticle(article);
    setLoading(false);
    setUrl("");

    setTimeout(() => setSteps(processingSteps), 1500);
  }, [url, publishArticle, generateArticleFromTranscript]);

  if (!authenticated) {
    return (
      <div className="min-h-screen flex items-center justify-center pt-16">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.4 }}
          className="w-full max-w-md mx-auto px-4"
        >
          <Card glow className="p-8 text-center">
            <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-cortex-500 to-accent-500 flex items-center justify-center mx-auto mb-6">
              <Lock className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-2xl font-bold text-white mb-2">Admin Access</h1>
            <p className="text-surface-400 text-sm mb-6">
              This tool is private. Enter your password to access the video-to-article engine.
            </p>
            <div className="space-y-3">
              <input
                type="password"
                placeholder="Enter password..."
                value={password}
                onChange={(e) => {
                  setPassword(e.target.value);
                  setAuthError(false);
                }}
                onKeyDown={(e) => e.key === "Enter" && handleAuth()}
                className="w-full px-4 py-3 bg-surface-900/50 border border-white/5 rounded-xl text-sm text-white placeholder-surface-500 focus:outline-none focus:border-cortex-500/50 focus:ring-1 focus:ring-cortex-500/30 transition-all text-center"
              />
              {authError && (
                <p className="text-xs text-red-400">Incorrect password</p>
              )}
              <Button onClick={handleAuth} className="w-full" size="lg">
                Unlock
              </Button>
            </div>
          </Card>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="pt-24 pb-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mb-10"
        >
          <Badge variant="primary" className="mb-4">
            <Sparkles className="w-3 h-3 mr-1" />
            Private Tool
          </Badge>
          <h1 className="text-3xl sm:text-4xl font-bold text-white mb-3">
            Video to Article Engine
          </h1>
          <p className="text-surface-400 max-w-2xl">
            Paste a YouTube, TikTok, or Instagram URL. The engine will extract the transcript,
            generate a full article, and publish it directly to the site.
          </p>
        </motion.div>

        {/* Platform badges */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="flex items-center gap-4 mb-6 text-sm text-surface-500"
        >
          <span className="flex items-center gap-1.5">
            <Youtube className="w-4 h-4 text-red-500" /> YouTube
          </span>
          <span className="flex items-center gap-1.5">
            <Music2 className="w-4 h-4 text-white" /> TikTok
          </span>
          <span className="flex items-center gap-1.5">
            <Instagram className="w-4 h-4 text-pink-400" /> Instagram
          </span>
        </motion.div>

        {/* URL Input */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15, duration: 0.5 }}
        >
          <Card glow className="p-6 sm:p-8 mb-8">
            <div className="flex items-center gap-2 mb-4">
              <input
                type="url"
                placeholder="Paste video URL here..."
                value={url}
                onChange={(e) => {
                  setUrl(e.target.value);
                  setError("");
                }}
                onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
                disabled={loading}
                className="flex-1 px-4 py-3.5 bg-surface-900/50 border border-white/5 rounded-xl text-sm text-white placeholder-surface-500 focus:outline-none focus:border-cortex-500/50 focus:ring-1 focus:ring-cortex-500/30 transition-all disabled:opacity-50"
              />
              <Button onClick={handleSubmit} loading={loading} size="lg">
                Process & Publish
                <ArrowRight className="w-4 h-4" />
              </Button>
            </div>
            {error && (
              <p className="text-xs text-red-400">{error}</p>
            )}
          </Card>
        </motion.div>

        {/* Processing sequence */}
        <AnimatePresence>
          {loading && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: "auto" }}
              exit={{ opacity: 0, height: 0 }}
            >
              <Card className="p-6 mb-8">
                <div className="relative py-4">
                  <div className="absolute left-[7px] top-0 bottom-0 w-px bg-white/5" />
                  <div className="space-y-6">
                    {steps.map((step, i) => (
                      <motion.div
                        key={step.id}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.15 }}
                        className="flex items-start gap-4"
                      >
                        <div className="relative z-10 flex items-center justify-center w-[18px] h-[18px]">
                          {step.status === "pending" && (
                            <div className="w-3 h-3 rounded-full border border-surface-600" />
                          )}
                          {step.status === "active" && (
                            <svg className="animate-spin w-4 h-4 text-cortex-400" viewBox="0 0 24 24">
                              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                            </svg>
                          )}
                          {step.status === "completed" && (
                            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                          )}
                        </div>
                        <p
                          className={`text-sm font-medium pt-px ${
                            step.status === "completed"
                              ? "text-emerald-400"
                              : step.status === "active"
                                ? "text-cortex-300"
                                : "text-surface-600"
                          }`}
                        >
                          {step.label}
                        </p>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </Card>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Published article success */}
        <AnimatePresence>
          {publishedArticle && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <Card glow className="p-6 sm:p-8 border-emerald-500/20">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center">
                    <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                  </div>
                  <div>
                    <h2 className="text-lg font-semibold text-white">Article Published</h2>
                    <p className="text-sm text-surface-500">
                      The article has been published to your site
                    </p>
                  </div>
                </div>

                <div className="bg-surface-900/50 rounded-xl p-4 mb-4 border border-white/5">
                  <p className="text-xs text-surface-500 mb-1">Title</p>
                  <p className="text-sm text-white font-medium">{publishedArticle.title}</p>
                  <p className="text-xs text-surface-500 mt-3 mb-1">Excerpt</p>
                  <p className="text-sm text-surface-400">{publishedArticle.excerpt}</p>
                  <div className="flex items-center gap-3 mt-3 text-xs text-surface-500">
                    <span>{publishedArticle.readTime} min read</span>
                    <span className="w-1 h-1 rounded-full bg-surface-600" />
                    <span>{publishedArticle.date}</span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <Link
                    href={`/articles/${publishedArticle.id}`}
                    className="inline-flex items-center gap-2 px-5 py-2.5 text-sm font-medium text-white bg-gradient-to-r from-cortex-500 to-accent-500 rounded-xl hover:from-cortex-400 hover:to-accent-400 transition-all"
                  >
                    <Eye className="w-4 h-4" />
                    View Published Article
                  </Link>
                  <Link
                    href="/articles"
                    className="inline-flex items-center gap-2 px-5 py-2.5 text-sm font-medium text-surface-300 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 hover:text-white transition-all"
                  >
                    All Articles
                    <ExternalLink className="w-4 h-4" />
                  </Link>
                </div>
              </Card>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Usage tips */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.5 }}
          className="mt-12 p-5 bg-surface-900/30 border border-white/5 rounded-2xl"
        >
          <h3 className="text-sm font-semibold text-white mb-3">How it works</h3>
          <div className="grid sm:grid-cols-3 gap-4 text-sm text-surface-500">
            <div>
              <span className="text-cortex-400 font-medium">1.</span> Paste any YouTube, TikTok, or Instagram video URL
            </div>
            <div>
              <span className="text-cortex-400 font-medium">2.</span> AI extracts the transcript and generates a full article
            </div>
            <div>
              <span className="text-cortex-400 font-medium">3.</span> The article is automatically published to your site
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
