import { notFound } from "next/navigation";
import { articles as staticArticles } from "@/lib/data";
import { ArticleDetailClient } from "@/components/articles/ArticleDetailClient";

export function generateStaticParams() {
  return staticArticles.map((article) => ({ slug: article.id }));
}

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const article = staticArticles.find((a) => a.id === slug);

  if (!article) {
    notFound();
  }

  return <ArticleDetailClient article={article} isAutoGenerated={false} />;
}
